destination: &cicd cicd
##############
# Application Custom Values
#############
# toggle between versions of the app by setting the tag to grey / purple or latest
pet_battle: &mesh_operators
  app_tag: latest
  # Could be over written in a jenkins file or your fork when doing CI/CD
  # image_repository: image-registry.openshift-image-registry.svc:5000
  # image_name: pet-battle
  # image_namespace: labs-ci-cd
  config_map: "'http://pet-battle-api-labs-test.apps.s43.core.rht-labs.com'"

pet_battle_api: &mesh_install
  appName: pet-battle-api
  image_repository: quay.io
  image_name: pet-battle-api
  image_namespace: eformat
  image_version: latest

##############
# Argo Ignore Differences
#############
#ignore_differences: &ignore_differences
#  ignoreDifferences:
#  - group: apps.openshift.io
#    kind: DeploymentConfig
#    jsonPointers:
#    - /spec/template/spec/containers/0/image
#    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
#    - /spec/triggers/1/imageChangeParams/lastTriggeredImage

##############
# Argo App of Apps declaration
#############
applications:
- name: mesh-operators
  enabled: true
  source: https://github.com/rcarrata/mesh-gitops.git
  source_path: mesh-operators
  sync_policy_automated: true
  destination: argocd
  source_ref: master
  no_helm: true
  #values: *front_end_values

- name: mesh-controlplane
  enabled: true
  source: https://github.com/rcarrata/mesh-gitops.git
  source_path: mesh-controlplane
  sync_policy_automated: true
  destination: argocd
  source_ref: master
  no_helm: true

#- name: pet-battle-api
#  enabled: true
#  source: https://github.com/eformat/pet-battle-api.git
#  source_path: chart
#  sync_policy_automated: true
#  destination: *test_ns
#  source_ref: master
#  values: *api_values
